<Row class-name="layout-breadcrumb">
    <Breadcrumb>
        <Breadcrumb-item href="#">租客服务</Breadcrumb-item>
        <Breadcrumb-item>租客列表</Breadcrumb-item>
    </Breadcrumb>
</Row>

<Row class-name="layout-filter">

    <i-form inline="true">
        <Form-item>数据筛选</Form-item>
        <Form-item style="width: 120px;">
            <i-input placeholder="Id" v-model="searchFilter.id"></i-input>
        </Form-item>
        <Form-item>
            <i-select placeholder="是否可用" v-model="searchFilter.isAvailable">
                <i-option value="1">是</i-option>
                <i-option value="0">否</i-option>
            </i-select>
        </Form-item>
        <Form-item style="width: 120px;">
            <i-input placeholder="公司名称" v-model="searchFilter.name"></i-input>
        </Form-item>

        <Form-item style="width: 120px;">
            <i-input placeholder="初始账号" v-model="searchFilter.account"></i-input>
        </Form-item>
        <Form-item>
            <i-input placeholder="城市" v-model="searchFilter.city"></i-input>
        </Form-item>
        <Form-item style="width: 120px;">
            <i-input placeholder="联系人" v-model="searchFilter.linkman"></i-input>
        </Form-item>
        <Form-item style="width: 120px;">
            <i-input placeholder="联系电话" v-model="searchFilter.contact"></i-input>
        </Form-item>
        <Form-item>
            <Date-picker type="daterange" placeholder="查询有效期开始" format="yyyy-MM-dd"
                         @on-change="searchFilter.beginAt_range=$event"
                         v-model="searchFilter.beginAt_range"></Date-picker>
        </Form-item>
        <Form-item>
            <Date-picker type="daterange" placeholder="查询有效期结束" format="yyyy-MM-dd"
                         @on-change="searchFilter.endAt_range=$event" v-model="searchFilter.endAt_range"></Date-picker>
        </Form-item>

        <Form-item>
            <i-button type="primary" @click="loadList(1, pageSize)">搜索</i-button>
            <i-button @click="resetFilter">重置</i-button>
        </Form-item>

    </i-form>

</Row>


<Row class-name="layout-content">
    <i-col class-name="layout-data-list">

        <Row class-name="layout-content-title">
            <i-col span="12">
                <h3>租客列表</h3>
            </i-col>
            <i-col span="12" class-name="align-right">
                <Button-group>

                    <i-button icon="android-create" type="ghost" v-on:click="location.href='/tenant/post'">创建租客</i-button>
                </Button-group>

            </i-col>
        </Row>

        <i-table :columns="columns" :data="data" @on-selection-change="selectionChange" :border="true"
                 @on-sort-change="remoteSort" stripe></i-table>


        <Row class="layout-content-page">

            <i-col span="10">
                <Button-group></Button-group>
            </i-col>

            <i-col span="14">
                <Row type="flex" justify="end">
                    <Page v-on:on-change="pageChange" size="small" v-on:on-page-size-change="sizeChange" :total="count"
                          :page-size="pageSize" :current="page" show-elevator show-total></Page>
                </Row>
            </i-col>

        </Row>

    </i-col>
</Row>

<script>
    (function () {
        "use strict";
        var tenant = new Janfish_DataList({
            el: "#app",
            methods: {
                modifyRemoteData: function (row) {
                    var _this = this;
                    _this.$http.post('/tenant/available', qs.stringify(row)).then(function (response) {
                        if (response.status !== "success") {
                            _this.$Message.error(response.message);
                            return false;
                        }
                        _this.$Message.success('操作成功');
                    });
                },
            },
            data: {
                api: {
                    search: '/tenant',
                    post: '/tenant/post',
                    remove: '/tenant/delete'
                },
                page: 1,
                pageSize: 12,
                searchFilter: {
                    "id": "",
                    "isAvailable": "",
                    "account": "",
                    "name": "",
                    "province": "",
                    "city": "",
                    "linkman": "",
                    "contact": "",
                    "beginAt_range": "",
                    "endAt_range": "",
                    "createdAt_range": ""
                },
                columns: [
                    {
                        type: 'selection',
                        width: 60,
                        align: 'center',
                        fixed: 'left'
                    },
                    {"sortable": "custom", "title": "Id", "key": "id", "width": 80},
                    {
                        "sortable": "custom",
                        "title": "是否可用",
                        "key": "isAvailable",
                        "width": 110,
                        "render": function (h, params) {
                            return h('i-switch', {
                                props: {
                                    value: params.row.isAvailable == '1'
                                },
                                on: {
                                    'on-change': function (val) {
                                        params.row.isAvailable = val === true ? '1' : '0';
                                        tenant.modifyRemoteData(params.row);
                                    }
                                }
                            })
                        }
                    },
                    {"sortable": "custom", "title": "公司名称", "key": "name"},
                    {
                        "sortable": "custom", "title": "省份",width: 90, "key": "province", render: function (h, params) {
                            return params.row.province || '-'
                        }
                    },
                    {
                        "sortable": "custom", "title": "城市",width: 90, "key": "city", render: function (h, params) {
                            return params.row.city || '-'
                        }
                    },
                    {
                        "sortable": "custom", "title": "联系人", "key": "linkman", width:100,render: function (h, params) {
                            return params.row.linkman || '-'
                        }
                    },
                    {
                        "sortable": "custom", "title": "联系电话",
                        "key": "contact",
                        "width": 120,
                        render: function (h, params) {
                            return params.row.contact || '-'
                        }
                    },
                    {
                        "sortable": "custom",
                        "title": "有效期开始",
                        "key": "beginAt",
                        "width": 160,
                        render: function (h, params) {
                            return params.row.beginAt || '-'
                        }
                    },
                    {
                        "sortable": "custom",
                        "title": "有效期结束",
                        "key": "endAt",
                        "width": 160,
                        render: function (h, params) {
                            return params.row.endAt || '-'
                        }
                    },
                    {"sortable": "custom", "title": "创建时间", "key": "createdAt", "width": 160},
                    {"sortable": "custom", "title": "更新时间", "key": "updatedAt", "width": 160},
                    {
                        title: '操作',
                        width: 160,
                        align: 'center',
                        key: 'operation',
                        fixed: 'right',
                        render: function (h, params) {
                            return h('ButtonGroup', [
                                h('Button', {
                                    props: {
                                        type: 'ghost',
                                        size: 'small'
                                    },

                                    on: {
                                        click: function () {
                                            location.href = "/tenant/post?id=" + params.row.id;
                                        }
                                    }
                                }, '编辑'),
                                h('Button', {
                                    props: {
                                        type: 'ghost',
                                        size: 'small'
                                    },
                                    on: {
                                        click: function () {
                                            location.href = "/tenant/view?id=" + params.row.id;
                                        }
                                    }
                                }, ' 详情'),
                                h('Button', {
                                    props: {
                                        type: 'ghost',
                                        size: 'small'
                                    },
                                    on: {
                                        click: function () {
                                            location.href = "/plugin/index?id=" + params.row.id;
                                        }
                                    }
                                }, '功能'),
                            ])
                        }
                    }

                ]
            },
            mounted: function () {
                this.setActiveMenu(["37", "38"]);
            }
        });

    }());

</script>