<Row class-name="layout-breadcrumb">
    <Breadcrumb>
        <Breadcrumb-item href="#">服务器管理</Breadcrumb-item>
        <Breadcrumb-item>服务器列表</Breadcrumb-item>
    </Breadcrumb>
</Row>

<Row class-name="layout-filter">

    <i-form inline="true">
        <Form-item>数据筛选</Form-item>

        <Form-item>
                <i-input placeholder="服务器名" v-model="searchFilter.name"></i-input>
        </Form-item>
        <Form-item>
                <i-input placeholder="服务器域名" v-model="searchFilter.domain"></i-input>
        </Form-item>
        <Form-item>
                <i-input placeholder="服务器IP" v-model="searchFilter.ip"></i-input>
        </Form-item>
        <Form-item>
        <Date-picker type="daterange" placeholder="查询创建时间" format="yyyy-MM-dd"  @on-change="searchFilter.createdAt_range=$event"  v-model="searchFilter.createdAt_range"></Date-picker>
        </Form-item>

        <Form-item>
            <i-button type="primary" @click="loadList(1, pageSize)">搜索</i-button>
            <i-button @click="resetFilter">重置</i-button>
        </Form-item>

    </i-form>

</Row>


<Row class-name="layout-content">
    <i-col class-name="layout-data-list">

        <Row class-name="layout-content-title">
            <i-col span="12">
                <h3>服务器列表</h3>
            </i-col>
            <i-col span="12" class-name="align-right">
                <Button-group>
                    
                    <i-button @click="removeBatch" type="ghost" icon="trash-b">批量删除</i-button>
                    <i-button icon="android-create" type="ghost" v-on:click="openPostModal('')">创建内容</i-button>
                    
                </Button-group>

            </i-col>
        </Row>

        <i-table :columns="columns" :data="data" @on-selection-change="selectionChange" :border="true" @on-sort-change="remoteSort" stripe></i-table>


        <Row class="layout-content-page">

            <i-col span="10">
                <Button-group></Button-group>
            </i-col>

            <i-col span="14">
                <Row type="flex" justify="end">
                    <Page v-on:on-change="pageChange" size="small" v-on:on-page-size-change="sizeChange" :total="count" :page-size="pageSize" :current="page" show-elevator show-total></Page>
                </Row>
            </i-col>

        </Row>

    </i-col>
</Row>



<template>
    <Modal :mask-closable="false" width="50%" ref="postPanel" v-model="showPost" title="创建内容" @on-ok="handleSubmit('form2')" @on-cancel="handleReset('form2')">
        <i-form ref="form2" :model="formData" :rules="validation" label-width="140">
                    <Form-item label="服务器名" prop="name">
                        <i-input v-model="formData.name" placeholder="请输入"></i-input>
                    </Form-item>

                    <Form-item label="服务器域名" prop="domain">
                        <i-input v-model="formData.domain" placeholder="请输入"></i-input>
                    </Form-item>

                    <Form-item label="服务器IP" prop="ip">
                        <i-input v-model="formData.ip" placeholder="请输入"></i-input>
                    </Form-item>

        </i-form>
        <div slot="footer">
            <i-button type="ghost" @click="handleReset('form2')" style="margin-left: 8px">取消</i-button>
            <i-button type="primary" @click="handleSubmit('form2')">提交</i-button>
        </div>
    </Modal>
</template>


<script>
    (function () {
        "use strict";
        var server = new Janfish_DataList({
            el: "#app",
            data: {
                
                validation:  {"name":[{"required":true,"message":"服务器名不能为空","trigger":"blur"},{"type":"string","max":50,"message":"服务器名长度应该在1-50","trigger":"blur"}],"domain":[{"type":"string","max":200,"message":"服务器域名长度应该在1-200","trigger":"blur"}],"ip":[{"type":"string","max":20,"message":"服务器IP长度应该在1-20","trigger":"blur"}]},
                
                api: {
                    search: '/server',
                
                    post: '/server/post',
                    remove: '/server/delete'
                    
                },
                page: 1,
                pageSize: 12,
                searchFilter: {"id":"","name":"","domain":"","ip":"","createdAt_range":""},
                columns: [
                
                    {
                        type: 'selection',
                        width: 60,
                        align: 'center',
                        fixed: 'left'
                    },
    
                    {"sortable":"custom","title":"Id","key":"id","width":80},
                    {"sortable":"custom","title":"服务器名","key":"name",render:function (h,params){
                        return params.row.name || '-'
                        }},
                    {"sortable":"custom","title":"服务器域名","key":"domain",render:function (h,params){
                            return params.row.domain || '-'
                        }},
                    {"sortable":"custom","title":"服务器IP","key":"ip",render:function (h,params){
                            return params.row.ip || '-'
                        }},
                    {"title":"服务数","key":"serviceCount",render:function (h,params){
                            return params.row.serviceCount
                        }},
                    {"title":"数据库数","key":"dbCount",render:function (h,params){
                            return params.row.dbCount
                        }},

                    {"sortable":"custom","title":"创建时间","key":"createdAt","width":160},
                    {"sortable":"custom","title":"更新时间","key":"updatedAt","width":160},
                    {
                        title: '操作',
                        width: 130,
                        align: 'center',
                        key: 'operation',
                        fixed: 'right',
                        render: function (h, params) {
                            return h('Row', [
                                h('Button', {
                                    props: {
                                        type: 'ghost',
                                        size: 'small'
                                    },
                                    style: {
                                        marginRight: '10px'
                                    },
                                    on: {
                                        click: function () {
                                            server.openPostModal(params.row.id)
                                        }
                                    }
                                }, '编辑'),
                                h('Button', {
                                    props: {
                                        type: 'ghost',
                                        size: 'small'
                                    },
                                    style: {},
                                    on: {
                                        click: function () {
                                            server.remove(params.row.id);
                                        }
                                    }
                                }, '删除')
                            ])
                        }
                    }
        
                ]
            },
            mounted: function () {
                this.setActiveMenu(["31","32"]);
            }
        });

    }());

</script>