<Row class-name="layout-breadcrumb">
    <Breadcrumb>
        <Breadcrumb-item href="#">server</Breadcrumb-item>
        <Breadcrumb-item href="/server">server</Breadcrumb-item>
        <Breadcrumb-item><template v-if="isNew">创建</template><template v-else>编辑</template>server</Breadcrumb-item>
    </Breadcrumb>
</Row>

<Row class-name="layout-content">

    <i-col class-name="layout-form">
        <Row class-name="layout-content-title">
            <i-col span="12">
                <h3><template v-if="isNew">创建</template><template v-else>编辑</template>server</h3>
            </i-col>
            <i-col span="12" class-name="align-right">
                <Button-group>
                    <i-button icon="ios-arrow-back" v-on:click="location.href='/server'">返回</i-button>
                </Button-group>
            </i-col>
        </Row>

        <Row class-name="layout-content-form">
            <i-col span="24">

                <i-form ref="form" :model="formData" :rules="validation" label-width="100">
                    <Form-item label="服务器名" prop="name">
                        <i-input v-model="formData.name" placeholder="请输入"></i-input>
                    </Form-item>

                    <Form-item label="服务器域名" prop="domain">
                        <i-input v-model="formData.domain" placeholder="请输入"></i-input>
                    </Form-item>

                    <Form-item label="服务器IP" prop="ip">
                        <i-input v-model="formData.ip" placeholder="请输入"></i-input>
                    </Form-item>


                    <Form-item>
                        <i-button type="primary" @click="handleSubmit('form')">提交</i-button>
                        <i-button type="ghost" @click="handleReset('form')" style="margin-left: 8px">重置</i-button>
                    </Form-item>

                </i-form>

            </i-col>

        </Row>

    </i-col>
</Row>
<script>

    (function () {
        "use strict";

        var server = new Janfish_DataPost({
            el: "#app",
            methods:{
                afterLoad:function(data){

                    return data;
                }
            },
            data: {
                validation:  {"name":[{"required":true,"message":"服务器名不能为空","trigger":"blur"},{"type":"string","max":50,"message":"服务器名长度应该在1-50","trigger":"blur"}],"domain":[{"type":"string","max":200,"message":"服务器域名长度应该在1-200","trigger":"blur"}],"ip":[{"type":"string","max":20,"message":"服务器IP长度应该在1-20","trigger":"blur"}]},
                api: {
                    post: '/server/post'
                }
            },
            mounted: function () {
                var _this = this;
                _this.setActiveMenu(["31","32"]);

             }
       })
    }());


</script>