<Row class-name="layout-breadcrumb">
    <Breadcrumb>
        <Breadcrumb-item href="#">服务列表</Breadcrumb-item>
        <Breadcrumb-item href="/service">服务列表</Breadcrumb-item>
        <Breadcrumb-item><template v-if="isNew">创建</template><template v-else>编辑</template>服务列表</Breadcrumb-item>
    </Breadcrumb>
</Row>

<Row class-name="layout-content">

    <i-col class-name="layout-form">
        <Row class-name="layout-content-title">
            <i-col span="12">
                <h3><template v-if="isNew">创建</template><template v-else>编辑</template>服务列表</h3>
            </i-col>
            <i-col span="12" class-name="align-right">
                <Button-group>
                    <i-button icon="ios-arrow-back" v-on:click="location.href='/service'">返回</i-button>
                </Button-group>
            </i-col>
        </Row>

        <Row class-name="layout-content-form">
            <i-col span="24">

                <i-form ref="form" :model="formData" :rules="validation" label-width="100">
                    <Form-item label="状态" prop="isAvailable">
                        <i-switch :value="formData.isAvailable==1" @on-change="function(status){ formData.isAvailable=status?1:0}"></i-switch>
                    </Form-item>

                    <Form-item label="服务器" prop="serverId">
                        <Input-number :min="0" v-model.number="formData.serverId"></Input-number>
                    </Form-item>

                    <Form-item label="服务名称" prop="name">
                        <i-input v-model="formData.name" placeholder="请输入"></i-input>
                    </Form-item>

                    <Form-item label="服务代号" prop="code">
                        <i-input v-model="formData.code" placeholder="请输入"></i-input>
                    </Form-item>

                    <Form-item label="服务tag，逗号隔开" prop="tag">
                        <i-input v-model="formData.tag" placeholder="请输入"></i-input>
                    </Form-item>

                    <Form-item label="服务地址" prop="host">
                        <i-input v-model="formData.host" placeholder="请输入"></i-input>
                    </Form-item>


                    <Form-item>
                        <i-button type="primary" @click="handleSubmit('form')">提交</i-button>
                        <i-button type="ghost" @click="handleReset('form')" style="margin-left: 8px">重置</i-button>
                    </Form-item>

                </i-form>

            </i-col>

        </Row>

    </i-col>
</Row>
<script>

    (function () {
        "use strict";

        var service = new Janfish_DataPost({
            el: "#app",
            methods:{
                afterLoad:function(data){

                    return data;
                }
            },
            data: {
                validation:  {"serverId":[{"required":true,"type":"integer","message":"请填写的整形数字","trigger":"blur"}],"name":[{"type":"string","max":50,"message":"服务名称长度应该在1-50","trigger":"blur"}],"code":[{"type":"string","max":50,"message":"服务代号长度应该在1-50","trigger":"blur"}],"tag":[{"type":"string","max":255,"message":"服务tag，逗号隔开长度应该在1-255","trigger":"blur"}],"host":[{"type":"string","max":200,"message":"服务地址长度应该在1-200","trigger":"blur"}]},
                api: {
                    post: '/service/post'
                }
            },
            mounted: function () {
                var _this = this;
                _this.setActiveMenu(["33","34"]);

             }
       })
    }());


</script>