<Row class-name="layout-content show404">
    <h1>很抱歉，您查找的页面不存在</h1>

    <div class="tips">

        <p>您可以：</p>

        <p> 1、检查访问的页面网址是否正确</p>

        <p> 2、返回到 <a href="#" @click="goBack">[上一页]</a></p>

    </div>
</Row>
<script>
    new Janfish({
        el: "#app",
        methods: {
            goBack: function () {
                if (document.referrer) {
                    history.back();
                } else {
                    location.href = '/';
                }
            }
        }
    });
</script>