<Row class-name="layout-breadcrumb">
    <Breadcrumb>
        <Breadcrumb-item href="#">系统管理</Breadcrumb-item>
        <Breadcrumb-item href="/administrator">管理员管理</Breadcrumb-item>
        <Breadcrumb-item><template v-if="isNew">创建</template><template v-else>编辑</template>管理员</Breadcrumb-item>
    </Breadcrumb>
</Row>
<Row class-name="layout-content">

    <i-col class-name="layout-form">


        <Row class-name="layout-content-title">
            <i-col span="12">
                <h3><template v-if="isNew">创建</template><template v-else>编辑</template>管理员</h3>
            </i-col>
            <i-col span="12" class-name="align-right">
                <Button-group>
                    <i-button icon="ios-arrow-back" v-on:click="location.href='/administrator'">返回</i-button>
                </Button-group>
            </i-col>
        </Row>

        <Row class-name="layout-content-form">
            <i-col span="24">

                <i-form ref="form" :model="formData" :rules="validation" label-width="100">

                    <Form-item label="帐号名" prop="name">
                        <template v-if="isNew">
                            <i-input v-model="formData.name" placeholder="请输入"></i-input>
                        </template>
                        <template v-else>
                            {{ formData.name }}
                        </template>
                    </Form-item>

                    <Form-item label="角色选择" prop="role_id" v-if="formData.name!=='administrator'">
                        <i-ajax-select model="\Application\Core\Models\AdministratorRole" attribute="name" v-model="formData.role_id"></i-ajax-select>
                    </Form-item>

                    <Form-item label="昵称" prop="nickname">
                        <i-input v-model="formData.nickname" placeholder="请输入"></i-input>
                    </Form-item>


                    <Form-item label="密码" prop="password">
                        <i-input type="password" v-model="formData.password" placeholder="请输入"></i-input>
                    </Form-item>

                    <Form-item>
                        <i-button type="primary" @click="handleSubmit('form')">提交</i-button>
                        <i-button type="ghost" @click="handleReset('form')" style="margin-left: 8px" v-if="isNew">重置</i-button>
                    </Form-item>

                </i-form>

            </i-col>

        </Row>

    </i-col>
</Row>
<script>

    (function () {
        "use strict";

        var administrator = new Janfish_DataPost({
            el: "#app",
            data: {
                api: {
                    post: '/administrator/post'
                },
                validation: {
                    name: [
                        {required: true, message: '姓名不能为空', trigger: 'blur'}
                    ],
                    nickname: [
                        {required: true, message: '昵称不能为空', trigger: 'blur'}
                    ],
                    password: [
                        {required: false, message: ' 密码不能为空', trigger: 'blur'}
                    ],
                    role_id: [
                        {required: true, message: ' 角色不能为空', trigger: 'blur'}
                    ]
                }
            },
            mounted: function () {
                this.setActiveMenu(['2', '27']);

            }
        })
    }());


</script>
