<Row class-name="layout-breadcrumb">
    <Breadcrumb>
        <Breadcrumb-item href="#">系统管理</Breadcrumb-item>
        <Breadcrumb-item>管理员角色管理</Breadcrumb-item>
    </Breadcrumb>
</Row>

<Row class-name="layout-filter">

    <i-form inline="true">
        <Form-item>数据筛选</Form-item>
        <Form-item>
            <i-input placeholder="角色名" v-model="searchFilter.name"></i-input>
        </Form-item>


        <Form-item>
            <i-button type="primary" @click="loadList(1, pageSize)">搜索</i-button>
            <i-button @click="resetFilter">重置</i-button>
        </Form-item>
    </i-form>

</Row>


<Row class-name="layout-content">
    <i-col class-name="layout-data-list">


        <Row class-name="layout-content-title">
            <i-col span="12">
                <h3>管理员角色管理</h3>
            </i-col>
            <i-col span="12" class-name="align-right">
                <Button-group>

                    <i-button @click="removeBatch" type="ghost" icon="trash-b">批量删除</i-button>
                    <i-button icon="android-create" type="ghost" v-on:click="location.href='/administratorRole/post'">添加角色</i-button>

                </Button-group>

            </i-col>
        </Row>

        <i-table :columns="columns" :data="data" @on-selection-change="selectionChange" :border="true" @on-sort-change="remoteSort" stripe></i-table>


        <Row class="layout-content-page">

            <i-col span="10">
                <Button-group></Button-group>
            </i-col>

            <i-col span="14">
                <Row type="flex" justify="end">
                    <Page v-on:on-change="pageChange" size="small" v-on:on-page-size-change="sizeChange" :total="count" :page-size="pageSize" :current="page" show-elevator show-total></Page>
                </Row>
            </i-col>

        </Row>

    </i-col>
</Row>
<script>
    (function () {
        "use strict";
        var administratorRole = new Janfish_DataList({
            el: "#app",
            data: {
                api: {
                    search: '/administratorRole',
                    remove: '/administratorRole/delete'
                },
                page: 1,
                pageSize: 12,
                searchFilter: {
                    name: ''
                },
                columns: [
                    {
                        type: 'selection',
                        width: 60,
                        align: 'center'
                    },
                    {
                        sortable: 'custom',
                        title: 'Id',
                        width: 80,
                        key: 'id'
                    },
                    {
                        title: '角色名',

                        key: 'name'
                    },

                    {
                        sortable: 'custom',
                        title: '创建',
                        width: 160,
                        key: 'createdAt'
                    },
                    {
                        sortable: 'custom',
                        title: '更新',
                        width: 160,
                        key: 'updatedAt'
                    },
                    {
                        title: '操作',
                        width: 130,
                        align: 'center',
                        key: 'operation',
                        render: function (h, params) {
                            return h('Row', [
                                h('Button', {
                                    props: {
                                        type: 'ghost',
                                        size: 'small'
                                    },
                                    style: {
                                        marginRight: '10px'
                                    },
                                    on: {
                                        click: function () {
                                            location.href = '/administratorRole/post?id=' + (params.row.id);
                                        }
                                    }
                                }, '编辑'),
                                h('Button', {
                                    props: {
                                        type: 'ghost',
//                                        type: 'error',
                                        size: 'small'
                                    },
                                    style: {},
                                    on: {
                                        click: function () {
                                            administratorRole.remove(params.row.id);
                                        }
                                    }
                                }, '删除')
                            ])
                        }
                    }
                ]
            },
            mounted: function () {
                this.setActiveMenu(['2', '28']);
            }
        });

    }());

</script>
